security:
  role_hierarchy:
      ROLE_ADMIN:       [ROLE_USER, ROLE_SUPER_ADMIN ]
      ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_SONATA_ADMIN, ROLE_ALLOWED_TO_SWITCH, ROLE_SUPER_ADMIN]

  firewalls:
      dev:
          pattern:  ^/(_(profiler|wdt)|css|images|js)/
          security: false

      secured_area:
          pattern:    ^/
          anonymous: ~
          form_login:
              login_path:  /login
              check_path:  /login_check
              default_target_path: app_index
          logout:
              path:   /logout
              target: /

  access_control:
      - { path: ^/admin, roles: ROLE_SUPER_ADMIN }

  providers:
      main:
          entity: { class: App\JoboardBundle\Entity\User, property: username }


  encoders:
      App\JoboardBundle\Entity\User: sha512