app_job_index:
    path:     /
    defaults: { _controller: "AppJoboardBundle:Job:index" }
    methods:  GET

app_job_show:
    path:  /{company}/{id}/{location}/{position}/
    defaults: { _controller: "AppJoboardBundle:Job:show" }

app_job_preview:
    path:  /{company}/{location}/{token}/{position}/
    defaults: { _controller: "AppJoboardBundle:Job:preview" }
    requirements:
        token:  \w+

app_job_create:
    path:  /create
    defaults: { _controller: "AppJoboardBundle:Job:create" }
    requirements: { _method: post }

app_job_edit:
    path:     /edit/{token}
    defaults: { _controller: "AppJoboardBundle:Job:edit" }
    methods:  [GET, POST]

app_job_update:
    path:  /{token}/update
    defaults: { _controller: "AppJoboardBundle:Job:update" }
    requirements: { _method: post|put }

app_job_delete:
    path:     /{token}/delete
    defaults: { _controller: "AppJoboardBundle:Job:delete" }
    methods:  DELETE

